import '../globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

const roboto = Roboto({
   subsets: ['latin'],
   weight: ['300','500','700'],
   variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable} w-2/4 m-auto`}>
        <h1 className='text-3xl font-header font-bold py-5'>Breadz</h1>
        
        <ul className='flex justify-center items-center rounded-full bg-primary text-white h-9'>
          <li>
            <Link className='py-2 px-5' href="/home">Home</Link>
          </li>
          <li>
            <Link className='py-2 px-5' href="/members">Members</Link>
          </li>
          <li>
            <Link className='py-2 px-5' href="/categories">Categories</Link>
          </li>
          <li>
            <Link className='py-2 px-5' href="/snacks">Snacks</Link>
          </li>
          <li>
            <Link className='py-2 px-5' href="/reports">Report</Link>
          </li>
          <li>
            <Link className='py-2 px-5' href="/settings">Settings</Link>
          </li>
        </ul>

        <div>{children}</div>
      </body>
    </html>
  )
}
