import '../globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

const roboto = Roboto({
   subsets: ['latin'],
   weight: ['300','500','700'],
   variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable} w-2/4 m-auto pt-20`}>
        <div>{children}</div>
      </body>
    </html>
  )
}
